// React Native Paper theme configuration — palette from login screen
import { MD3Theme } from 'react-native-paper';
import { Colors } from '@/constants/theme';

const COL = Colors.light;
const CD = Colors.dark;

export const paperTheme: MD3Theme = {
  version: 3,
  isV3: true,
  dark: false,
  roundness: 12,
  colors: {
    primary: COL.primary,
    primaryContainer: COL.primaryLight,
    secondary: COL.secondary,
    secondaryContainer: COL.secondaryLight,
    tertiary: '#7C3AED',
    tertiaryContainer: '#F3E8FF',
    error: COL.error,
    errorContainer: COL.errorLight,
    background: COL.background,
    surface: COL.surface,
    surfaceVariant: COL.surfaceVariant,
    surfaceDisabled: COL.disabledBackground,
    onPrimary: COL.textOnPrimary,
    onPrimaryContainer: '#047857',
    onSecondary: COL.textOnSecondary,
    onSecondaryContainer: '#0369A1',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#4C1D95',
    onError: '#FFFFFF',
    onErrorContainer: '#7F1D1D',
    onBackground: COL.text,
    onSurface: COL.text,
    onSurfaceVariant: COL.textSecondary,
    onSurfaceDisabled: COL.textTertiary,
    outline: COL.border,
    outlineVariant: COL.borderDark,
    inverseSurface: '#1E293B',
    inverseOnSurface: '#F1F5F9',
    inversePrimary: '#4DA3FF',
    shadow: 'rgba(0, 0, 0, 0.1)',
    scrim: 'rgba(0, 0, 0, 0.5)',
    backdrop: 'rgba(0, 0, 0, 0.5)',
  },
  fonts: {
    displayLarge: { fontFamily: 'System', fontWeight: '700', fontSize: 48, lineHeight: 56, letterSpacing: 0 },
    displayMedium: { fontFamily: 'System', fontWeight: '600', fontSize: 36, lineHeight: 44, letterSpacing: 0 },
    displaySmall: { fontFamily: 'System', fontWeight: '600', fontSize: 32, lineHeight: 40, letterSpacing: 0 },
    headlineLarge: { fontFamily: 'System', fontWeight: '600', fontSize: 24, lineHeight: 32, letterSpacing: 0 },
    headlineMedium: { fontFamily: 'System', fontWeight: '600', fontSize: 20, lineHeight: 28, letterSpacing: 0 },
    headlineSmall: { fontFamily: 'System', fontWeight: '600', fontSize: 18, lineHeight: 24, letterSpacing: 0 },
    titleLarge: { fontFamily: 'System', fontWeight: '600', fontSize: 20, lineHeight: 28, letterSpacing: 0 },
    titleMedium: { fontFamily: 'System', fontWeight: '600', fontSize: 16, lineHeight: 24, letterSpacing: 0.15 },
    titleSmall: { fontFamily: 'System', fontWeight: '600', fontSize: 14, lineHeight: 20, letterSpacing: 0.1 },
    bodyLarge: { fontFamily: 'System', fontWeight: '400', fontSize: 16, lineHeight: 24, letterSpacing: 0.5 },
    bodyMedium: { fontFamily: 'System', fontWeight: '400', fontSize: 14, lineHeight: 20, letterSpacing: 0.25 },
    bodySmall: { fontFamily: 'System', fontWeight: '400', fontSize: 12, lineHeight: 16, letterSpacing: 0.4 },
    labelLarge: { fontFamily: 'System', fontWeight: '600', fontSize: 14, lineHeight: 20, letterSpacing: 0.1 },
    labelMedium: { fontFamily: 'System', fontWeight: '600', fontSize: 12, lineHeight: 16, letterSpacing: 0.5 },
    labelSmall: { fontFamily: 'System', fontWeight: '600', fontSize: 11, lineHeight: 16, letterSpacing: 0.5 },
  },
  animation: { scale: 1.0 },
};

export const paperDarkTheme: MD3Theme = {
  ...paperTheme,
  dark: true,
  colors: {
    ...paperTheme.colors,
    primary: CD.primary,
    primaryContainer: CD.primaryLight,
    secondary: CD.secondary,
    secondaryContainer: CD.secondaryLight,
    error: CD.error,
    errorContainer: CD.errorLight,
    background: CD.background,
    surface: CD.surface,
    surfaceVariant: CD.surfaceVariant,
    surfaceDisabled: CD.disabledBackground,
    onPrimary: CD.textOnPrimary,
    onPrimaryContainer: '#DCFCE7',
    onSecondary: CD.textOnSecondary,
    onSecondaryContainer: '#E0F2FE',
    onError: '#FFFFFF',
    onErrorContainer: '#FEF2F2',
    onBackground: CD.text,
    onSurface: CD.text,
    onSurfaceVariant: CD.textSecondary,
    onSurfaceDisabled: CD.textTertiary,
    outline: CD.border,
    outlineVariant: CD.borderDark,
    inverseSurface: '#F1F5F9',
    inverseOnSurface: '#0F172A',
    inversePrimary: '#16A34A',
    shadow: 'rgba(0, 0, 0, 0.3)',
    scrim: 'rgba(0, 0, 0, 0.7)',
    backdrop: 'rgba(0, 0, 0, 0.7)',
  },
};